name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm run install:all

    - name: Build application
      run: npm run build

    - name: Run tests
      run: |
        # Run client tests
        cd client && npm test -- --coverage --watchAll=false
      continue-on-error: true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          dist/
          client/build/
        retention-days: 1

  deploy-dev:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [test]
    uses: ./.github/workflows/deploy-application.yml
    with:
      environment: 'dev'
    secrets: inherit